
package com.mulesoft.samples;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:34:58.465-06:00
 * Generated source version: 2.5.1
 * 
 */
public final class IWorkOrderCompletion_BasicHttpBindingIWorkOrderCompletion_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WorkOrderCompletion");

    private IWorkOrderCompletion_BasicHttpBindingIWorkOrderCompletion_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WorkOrderCompletion.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WorkOrderCompletion ss = new WorkOrderCompletion(wsdlURL, SERVICE_NAME);
        IWorkOrderCompletion port = ss.getBasicHttpBindingIWorkOrderCompletion();  
        
        {
        System.out.println("Invoking completeWorkOrder...");
        com.mulesoft.samples.WorkOrderCompleteRequest _completeWorkOrder_wo = null;
        com.mulesoft.samples.WorkOrderCompleteResponse _completeWorkOrder__return = port.completeWorkOrder(_completeWorkOrder_wo);
        System.out.println("completeWorkOrder.result=" + _completeWorkOrder__return);


        }

        System.exit(0);
    }

}
