package com.mulesoft.samples;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:34:58.484-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IWorkOrderCompletion")
@XmlSeeAlso({ObjectFactory.class})
public interface IWorkOrderCompletion {

    @WebResult(name = "CompleteWorkOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IWorkOrderCompletion/CompleteWorkOrder", output = "http://tempuri.org/IWorkOrderCompletion/CompleteWorkOrderResponse")
    @RequestWrapper(localName = "CompleteWorkOrder", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.samples.CompleteWorkOrder")
    @WebMethod(operationName = "CompleteWorkOrder", action = "http://tempuri.org/IWorkOrderCompletion/CompleteWorkOrder")
    @ResponseWrapper(localName = "CompleteWorkOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.samples.CompleteWorkOrderResponse")
    public com.mulesoft.samples.WorkOrderCompleteResponse completeWorkOrder(
        @WebParam(name = "wo", targetNamespace = "http://tempuri.org/")
        com.mulesoft.samples.WorkOrderCompleteRequest wo
    );
}
