package com.mulesoft.samples;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:34:58.497-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "WorkOrderCompletion", 
                  wsdlLocation = "http://localhost:8082/WorkOrderCompletion?singleWsdl",
                  targetNamespace = "http://tempuri.org/") 
public class WorkOrderCompletion extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WorkOrderCompletion");
    public final static QName BasicHttpBindingIWorkOrderCompletion = new QName("http://tempuri.org/", "BasicHttpBinding_IWorkOrderCompletion");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8082/WorkOrderCompletion?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkOrderCompletion.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8082/WorkOrderCompletion?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkOrderCompletion(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkOrderCompletion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkOrderCompletion() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WorkOrderCompletion(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WorkOrderCompletion(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WorkOrderCompletion(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IWorkOrderCompletion
     */
    @WebEndpoint(name = "BasicHttpBinding_IWorkOrderCompletion")
    public IWorkOrderCompletion getBasicHttpBindingIWorkOrderCompletion() {
        return super.getPort(BasicHttpBindingIWorkOrderCompletion, IWorkOrderCompletion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWorkOrderCompletion
     */
    @WebEndpoint(name = "BasicHttpBinding_IWorkOrderCompletion")
    public IWorkOrderCompletion getBasicHttpBindingIWorkOrderCompletion(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIWorkOrderCompletion, IWorkOrderCompletion.class, features);
    }

}
