package com.mulesoft.samples.generalledger;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:38:40.729-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "GeneralLedgerService", 
                  wsdlLocation = "http://localhost:8085/GeneralLedgerService?singleWsdl",
                  targetNamespace = "http://tempuri.org/") 
public class GeneralLedgerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GeneralLedgerService");
    public final static QName BasicHttpBindingIGeneralLedgerService = new QName("http://tempuri.org/", "BasicHttpBinding_IGeneralLedgerService");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/GeneralLedgerService?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneralLedgerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/GeneralLedgerService?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneralLedgerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneralLedgerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralLedgerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneralLedgerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneralLedgerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneralLedgerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IGeneralLedgerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IGeneralLedgerService")
    public IGeneralLedgerService getBasicHttpBindingIGeneralLedgerService() {
        return super.getPort(BasicHttpBindingIGeneralLedgerService, IGeneralLedgerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGeneralLedgerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IGeneralLedgerService")
    public IGeneralLedgerService getBasicHttpBindingIGeneralLedgerService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIGeneralLedgerService, IGeneralLedgerService.class, features);
    }

}
