
package com.mulesoft.samples.generalledger;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:38:40.707-06:00
 * Generated source version: 2.5.1
 * 
 */
public final class IGeneralLedgerService_BasicHttpBindingIGeneralLedgerService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "GeneralLedgerService");

    private IGeneralLedgerService_BasicHttpBindingIGeneralLedgerService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GeneralLedgerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GeneralLedgerService ss = new GeneralLedgerService(wsdlURL, SERVICE_NAME);
        IGeneralLedgerService port = ss.getBasicHttpBindingIGeneralLedgerService();  
        
        {
        System.out.println("Invoking processGL...");
        com.mulesoft.samples.generalledger.TimeSheetForGL _processGL_gl = null;
        com.mulesoft.samples.generalledger.TimeSheetForGLResponse _processGL__return = port.processGL(_processGL_gl);
        System.out.println("processGL.result=" + _processGL__return);


        }

        System.exit(0);
    }

}
