package com.mulesoft.samples.generalledger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-05T21:38:40.720-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IGeneralLedgerService")
@XmlSeeAlso({ObjectFactory.class})
public interface IGeneralLedgerService {

    @WebResult(name = "ProcessGLResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGeneralLedgerService/ProcessGL", output = "http://tempuri.org/IGeneralLedgerService/ProcessGLResponse")
    @RequestWrapper(localName = "ProcessGL", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.samples.generalledger.ProcessGL")
    @WebMethod(operationName = "ProcessGL", action = "http://tempuri.org/IGeneralLedgerService/ProcessGL")
    @ResponseWrapper(localName = "ProcessGLResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.samples.generalledger.ProcessGLResponse")
    public com.mulesoft.samples.generalledger.TimeSheetForGLResponse processGL(
        @WebParam(name = "gl", targetNamespace = "http://tempuri.org/")
        com.mulesoft.samples.generalledger.TimeSheetForGL gl
    );
}
